version: 0.2

phases:
 pre_build:
  commands:
    - echo "insatlling maven"
    - apt-get-install -y maven
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
  #- '**/*'
    - target/StockPricesApp-0.0.1-SNAPSHOT.jar
  discard-paths: yes

